#!/usr/bin/python3

from xml.etree import ElementTree as ET
import requests

LAT = 59.9168873
LON = 10.7287067
URL = f"https://api.met.no/weatherapi/locationforecast/2.0/compact?lat={LAT}&lon={LON}"

CLIENT_ID = "6930df44-167c-46b4-9c27-9d2cee99e8e6"

def fetch_url_content(url):
    user_agent = "Client-ID " + CLIENT_ID
    headers = {"User-Agent": user_agent}
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    return response.json()

resp = fetch_url_content(URL)
details = resp['properties']['timeseries'][0]['data']['instant']['details']
temperature = details['air_temperature']
wind_speed = details['wind_speed']
wind_direction = details['wind_from_direction']
cloud_area_fraction = int(details['cloud_area_fraction'])
relative_humidity = int(details['relative_humidity'])
percipitation_amount = 0
try:
    percipitation_amount = details['precipitation_amount']
except KeyError:
    pass

parts = [
    f"{temperature}",
    f" {relative_humidity}%",
    f"󱨵  {cloud_area_fraction}%",
]

if percipitation_amount > 0:
    parts.append(f" {percipitation_amount}mm")

print (" | ".join(parts))

